             Console.ForegroundColor = ConsoleColor.Blue;
             Console.WriteLine("Reviso meus Planos - Maneva");
             Console.ResetColor();
             Console.WriteLine("");
             Console.WriteLine("Reviso meus planos e até meus enganos");
             Console.WriteLine("Todos me levaram a você");
             Console.WriteLine("Um cara sem rumo de hábitos noturnos");
             Console.WriteLine("Que só procurava prazer");
             Console.WriteLine("Um brinco de pena, um par de estrelas negras");
             Console.WriteLine("Se chora até faz chover");
             Console.WriteLine("Meu cabelo comprido cobre o fone de ouvido");
             Console.WriteLine("E a barba sempre por fazer");
             Console.WriteLine("");
             Console.ForegroundColor = ConsoleColor.Green;
             Console.WriteLine("O destino uniu nossos caminhos");
             Console.WriteLine("Mistura de amor e prazer");
             Console.WriteLine("Posso até assistir nossos filhos");
             Console.WriteLine("E como eles irão crescer");
             Console.ResetColor();
             Console.WriteLine("");
             Console.WriteLine("Reparo em seus traços");
             Console.WriteLine("Refaço meus passos, e sei que meu mundo é você");
             Console.WriteLine("Mudou minha vida, curou minhas feridas");
             Console.WriteLine("Sem mesmo dizer o porquê");
             Console.WriteLine("");
             Console.WriteLine("Serei seu espaço, serei sempre grato");
             Console.WriteLine("Por ter me ensinado a viver");
             Console.WriteLine("És o que preciso, loucura e abrigo");
             Console.WriteLine("Morar no teu jeito de ser");
             Console.WriteLine("");